apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesJson6902:
- target:
    version: v1
    kind: CustomResourceDefinition
    name: tasks.core.rageta.io
  patch: |
    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/steps/items/properties/filter/oneOf/-
      value:
        required: [buffer]
    - op: add
      path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/steps/items/properties/filter/properties/buffer
      value:
        type: object
        properties:
          bufferField:
            type: string
          maxMessages:
            type: number
          maxTime:
            type: string
